### ISSUE TITLE
Implementation étude cas c#

### ISSUE THREAD

**Issue by JJeanniard** [JJeanniard/DWWM_2005#29]
Réalisation de l'implementation en C# des l'études de cas:

- [ ] Académie de l'issue #16 
- [ ] Enterprise de l'issue #14 
- [ ] Voiture de l'issue #18
- [ ] Réservation de vol #19
